version: '3.7'

services:
  main:
    container_name: chatting-app-backend
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - database
    environment:
      DB_HOST: database
      DATABASE_URL: mysql://admin:postgres@database:3306/chatting
    links:
      - database:database
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3307:3306"